name: SonarCloud

on:
  push:
    branches:
      - develop
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Make Gradlew executable
      run: chmod +x gradlew
      working-directory: lab3

    - name: Build with Gradle
      working-directory: lab3
      run: ./gradlew build

    - name: Run Tests
      working-directory: lab3
      run: ./gradlew test

  sonarcloud:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v3.0.0
      env:
        SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
            